test("test fail", () => {
  expect(fail()).toThrow("complete failure");
});
